### ISSUE TITLE
Keep a Changelog

### ISSUE THREAD

**Issue by cvrebert** [sindresorhus/load-grunt-tasks#32]
Either as notes in the [GitHub Releases](https://github.com/sindresorhus/load-grunt-tasks/releases), or as a `CHANGELOG.md` file, or whatever.

**Comment by sindresorhus** [comment]
I usually do on larger modules, but on small ones like this it's easier to just read the commit log.

**Comment by cvrebert** [comment]
:imp:  It might be small, but it's very widely used.

**Comment by sindresorhus** [comment]
Small, as in size, not popularity, meaning the commit log is clean enough to be easily readable.

**Comment by cvrebert** [comment]
Yes, that's what I too meant by "small".
Still breaks convention and workflow though.
