### ISSUE TITLE
Local Npm module "grunt-XXXXX" not found. Is it installed?

### ISSUE THREAD

**Issue by paulca55** [sindresorhus/load-grunt-tasks#36]
The plugin works fine for me until I uninstall a grunt plugin. Once I do this and run any task I get the following errors. The uninstall seems to have worked as they are no longer in my node_modules folder but it must be still being reference somewhere, but not in my Gruntfile.js as I only have the require('load-grunt-tasks')(grunt); command specified. Any ideas?

![capture](https://cloud.githubusercontent.com/assets/7057526/7370375/a32e086e-edb1-11e4-9e28-93fee9e43977.JPG)

**Comment by kevva** [comment]
Have you looked in your `package.json`?

**Comment by paulca55** [comment]
I can't believe it was that simple and I didn't think of it. Thanks a lot :)
