### ISSUE TITLE
Request: support for svnDependencies

### ISSUE THREAD

**Issue by Askelkana** [sindresorhus/load-grunt-tasks#37]
The [svn-npm-crutch](https://github.com/jtrussell/svn-npm-crutch) module provides support for registering svn-based module dependencies. Would be nice if this module recognised those grunt modules too.

**Comment by sindresorhus** [comment]
No thanks.

**Comment by Askelkana** [comment]
Fair enough, but can you give reasons why not? It's not as if svn is some obscure tool that no-one's heard of.

Would it be worth my time making a pull request?

**Comment by sindresorhus** [comment]
You're asking me to support a non-standard package.json extension. I'm not interested in that. This supports whatever normal package.json supports. No thanks to a PR. You're better off forking ;)

**Comment by mario-st** [comment]
@Askelkana it's easy to implement:

```javascript
    require("load-grunt-tasks")(grunt, {
        requireResolution: true,
        scope: [
            'svnDependencies',
            'dependencies',
            'devDependencies',
            'peerDependencies',
            'optionalDependencies'
        ]
    });
```
Today I went into the same issue ;-)

**Comment by Askelkana** [comment]
Sure, I forked my own solution (exactly as you have it). I was just suggesting making it into the master rather than my own forked version.
