### ISSUE TITLE
Default to only `scope: 'dependencies'` when NODE_ENV="production"

### ISSUE THREAD

**Issue by edmorley** [sindresorhus/load-grunt-tasks#39]
In production we only need a subset of the packages installed, so I've put packages relating to deploying in `dependencies` and those relating to testing/development in `devDependencies`. Prod will then use `npm install --production` compared to `npm install` used locally.

However prod then needs the following in Gruntfile.js:
```js
require('load-grunt-tasks')(grunt, {scope: 'dependencies'});
```

...whereas locally I would need:
```js
require('load-grunt-tasks')(grunt);
```

But the latter then results in errors like this on production:
```bash
>> Local Npm module "grunt-eslint" not found. Is it installed?
>> Local Npm module "grunt-html-angular-validate" not found. Is it installed?
```

What would be great, is if load-grunt-tasks used the value of NODE_ENV or `--production` (or some other alternative) to determine which of the above to default to, when `scope` isn't specified.

This would avoid having to use this pattern:
```js
    if (grunt.option('production')) {
        require('load-grunt-tasks')(grunt, {scope: 'dependencies'});
    } else {
        require('load-grunt-tasks')(grunt);
    }
```

...and would then go along nicely with the behaviour of `npm install --production` (which only installs packages from `dependencies` and not `devDependencies`).

**Comment by edmorley** [comment]
Or alternatively I'm really looking for "load all tasks that exist in package.json but don't complain if some are missing".

**Comment by sindresorhus** [comment]
One of the most important things when deploying is that production should be as identical to dev/staging as possible. Also everything regarding deploying should be a devDependency. Only your application should use `dependencies`. I'm not interested in supporting an anti-pattern like yours. You can easily achieve this with: `require('load-grunt-tasks')(grunt, {scope: grunt.option('production') ? 'dependencies' :'devDependencies'});`.

**Comment by edmorley** [comment]
> everything regarding deploying should be a devDependency. Only your application should use dependencies. I'm not interested in supporting an anti-pattern like yours.

Thank you for your reply. I'd like to avoid anti-patterns if we're using any, but I don't believe we are - it's just that using node as a build system for a non-node app on Heroku doesn't fit the typical node-app workflow. (Either way our use-case is probably too specific to warrant support in load-grunt-tasks, so closing this issue is likely appropriate).

Our application is a python webapp that uses static assets built using grunt plugins. Our 'node app' is purely a build/testing system (and is never going to be published to npm, or be have downstream npm package consumers). So when you say "only your application should use dependencies" - well our node application **is** the build system.

> One of the most important things when deploying is that production should be as identical to dev/staging as possible.

Nodejs isn't installed on any webhead or worker node in production - it's only used on the machine that does the deploy. That machine has no need to have karma and related plugins installed, since it doesn't run the test suite/linters - they're run on Travis (and Heroku waits until they are passing before initiating the deploy; the grunt build steps will have already been tested).

We're going to be using `npm shrinkwrap` so the contents of `dependencies` (ie all packages apart from the karma related ones) will be identical on prod/state/locally. Is there still then risk for behaviour differences by not installing karma et al (ie: the contents of `devDependencies`) on the node that does the deploy? npm specifically nests sub-dependencies of packages, so that packages can't cause version conflicts - and by using npm shrinkwrap we ensure local=stage=prod.

Is there another way you'd suggest we do this? (I know another approach would be to commit the output of the grunt build to the repository - and in fact that's what we do at present - but that has many other disadvantages, so we're moving away from it).

Or to step back a moment and forget our specific use case - is there ever a time when it might be valid for a consumer of a node app to want to run Grunt tasks defined within that app's `Gruntfile.js`? (Since they'd only have `dependencies` installed and not `devDependencies`). Or is Grunt only ever expected to be used by the maintainers of a package/app, and thus why using it like we do (and I'd posit many other people) doesn't fit within the node ecosystem?

Thanks :-)

**Comment by patricknelson** [comment]
I concur; if only `load-grunt-tasks` actually cared about the environment, that would be pretty helpful. If I'm running `npm install --production` naturally I'd only expect grunt tasks associated with the current environment to be loaded. Logically I've already ensured that environment specific tasks would be run in said environment (e.g. I will not be running `browserSync` on my production server!).

When running my build, all I should have to do is run `NODE_ENV=production grunt build` (or set my environment variable some other way) and be done with it.
