### ISSUE TITLE
Not an issue but a code-maintainability warning

### ISSUE THREAD

**Issue by lukepuplett** [sindresorhus/load-grunt-tasks#43]
One of our developers used this plugin to auto-wire-up the npm packages to our gruntfile.

The problem is now that we want to clean-up the gruntfile and prune no-longer-used npm dependencies.

Alas we can no longer explicitly see which ones we are using from our gruntfile. I now have to manually trace them back.

**Comment by sindresorhus** [comment]
Run `$ grunt --verbose | grep 'local Npm module tasks'` to see which external tasks grunt loads.

Does that help?
