### ISSUE TITLE
When having the node_modules on a different folder, the plugin is unable to find those

### ISSUE THREAD

**Issue by martuanez** [sindresorhus/load-grunt-tasks#46]
Hi I've this workspace were we have different folders each with it's own gruntfile, they're different apps, 
The plugin allows me to set the path for the package.json file but it doesn't for the node_modules folder it doesn't even try to lok for it on the same folder level as the package.json, I think this is something that deserves to be included since the node_modules folder tends to be huge, real huge... By now we'll work with links...

Thanks,

Martin

**Comment by sindresorhus** [comment]
package.json and the node_modules folder are always in the same folder. That's how Node.js works and nothing to do with this plugin or grunt. Adding non-standard functionality like that is beyond the scope of this plugin.

**Comment by martuanez** [comment]
That's my point, it's not looking for the node_modules in the same folder as the packages.json.

**Comment by martuanez** [comment]
I would expect the plugin to find it on the same path I gave it for the package.json or to at least let me state were the folder is, being the first option good enough.
