### ISSUE TITLE
Bug when loading plugin with scope in the name.

### ISSUE THREAD

**Issue by kownacki** [sindresorhus/load-grunt-tasks#49]
```
require("load-grunt-tasks")(grunt, {requireResolution: true});
```

When using `requireResolution` on true, it doesn't load packages with scope in the name like @scope/grunt-my-plugin. 

In your code, this expression: `resolvePkg(path.join(pkgName, 'tasks')` evaluates to `null`.

**Comment by sindresorhus** [comment]
Seems [`resolve-pkg`](https://github.com/sindresorhus/resolve-pkg) doesn't handle scoped packages.

**Comment by sindresorhus** [comment]
Was fixed by https://github.com/sindresorhus/resolve-pkg/commit/81e9c552e526febe59b039ba73124951baea84cd.

**Comment by kownacki** [comment]
+1

**Comment by kownacki** [comment]
Thanks!
