### ISSUE TITLE
Grunt Load Task Peer Dependency 

### ISSUE THREAD

**Issue by jgacuca567** [sindresorhus/load-grunt-tasks#52]
@sindresorhus 

**Load-Grunt-Tasks** `3.5.2` requires **Grunt** `1.0.1` however when I install grunt, it brings up the peer inavalid error. I checked your package.json and everything seems fine. 

What would cause the error?

**Comment by sindresorhus** [comment]
npm issues should be reported at https://github.com/npm/npm/issues
