### ISSUE TITLE
Listing grunt tasks fails for v4.0.0

### ISSUE THREAD

**Issue by Klyner007** [sindresorhus/load-grunt-tasks#57]
The following error appeared once using the latest version:

Failed to list grunt tasks in mti\Gruntfile.js: failed to parse tasks from json
 * Edit settings

Reading "Gruntfile.js" Gruntfile...OK

Registering Gruntfile tasks.
Loading "Gruntfile.js" tasks...ERROR
>> SyntaxError: Unexpected token =
>>   at exports.runInThisContext (vm.js:53:16)
>>   at Module._compile (module.js:387:25)
>>   at Object.Module._extensions..js (module.js:422:10)
>>   at Module.load (C:\workspace\mti\node_modules\coffeescript\lib\coffee-script\register.js:45:36)
>>   at Function.Module._load (module.js:314:12)
>>   at Module.require (module.js:367:17)
>>   at require (internal/module.js:20:19)
>>   at Object.module.exports (C:\workspace\mti\Gruntfile.js:3:3)
>>   at loadTask (C:\workspace\mti\node_modules\grunt\lib\grunt\task.js:315:10)
>>   at Task.task.init (C:\workspace\mti\node_modules\grunt\lib\grunt\task.js:434:5)
>>   at Object.grunt.tasks (C:\workspace\mti\node_modules\grunt\lib\grunt.js:111:8)
>>   at Object.module.exports [as cli] (C:\workspace\mti\node_modules\grunt\lib\grunt\cli.js:27:9)
>>   at Object.<anonymous> (C:\workspace\mti\node_modules\grunt-cli\bin\grunt:44:20)
>>   at Module._compile (module.js:413:34)
>>   at Object.Module._extensions..js (module.js:422:10)
>>   at Module.load (module.js:357:32)
>>   at Function.Module._load (module.js:314:12)
>>   at Function.Module.runMain (module.js:447:10)
>>   at startup (node.js:148:18)
>>   at node.js:405:3

**Comment by sindresorhus** [comment]
Closing as it seems more related to your setup and no one else has reported this.
